package com.erp.domain.domainaudit.entity;

public enum DomainAuditAction {
    KID_APPLICATION_WAITLISTED,
    KID_APPLICATION_OFFERED,
    KID_APPLICATION_OFFER_ACCEPTED,
    KID_APPLICATION_APPROVED,
    KID_APPLICATION_REJECTED,
    KID_APPLICATION_CANCELLED,
    KID_APPLICATION_OFFER_EXPIRED,
    KINDERGARTEN_APPLICATION_APPROVED,
    KINDERGARTEN_APPLICATION_REJECTED,
    ANNOUNCEMENT_UPDATED,
    ANNOUNCEMENT_DELETED,
    ATTENDANCE_CHANGE_REQUEST_SUBMITTED,
    ATTENDANCE_CHANGE_REQUEST_APPROVED,
    ATTENDANCE_CHANGE_REQUEST_REJECTED,
    ATTENDANCE_CHANGE_REQUEST_CANCELLED,
    NOTIFICATION_OUTBOX_RETRIED
}
